[project]
name = "spotify-api-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.18",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
